version: '3'

services:
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
#  web:
#    build: .
#    command: ./start-server.sh
#    volumes:c
#      - .:/code/
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres_db
#    env_file:
#      - ./.env